2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Configure stats pid to 20162
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Loading settings from /home/yasin/.config/wandb/settings
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Loading settings from /home/yasin/notebooks/phi4/wandb/settings
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/home/yasin/notebooks/phi4/train.py'}
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_init.py:_log_setup():524] Logging user logs to /home/yasin/notebooks/phi4/wandb/run-20231019_113454-thuvhn7s/logs/debug.log
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_init.py:_log_setup():525] Logging internal logs to /home/yasin/notebooks/phi4/wandb/run-20231019_113454-thuvhn7s/logs/debug-internal.log
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_init.py:init():564] calling init triggers
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 4e-06, 'batch_size': 8000, 'architecture': 'z2nice'}
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_init.py:init():614] starting backend
2023-10-19 11:34:54,431 INFO    MainThread:20162 [wandb_init.py:init():618] setting up manager
2023-10-19 11:34:54,432 INFO    MainThread:20162 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-19 11:34:54,433 INFO    MainThread:20162 [wandb_init.py:init():624] backend started and connected
2023-10-19 11:34:54,437 INFO    MainThread:20162 [wandb_init.py:init():715] updated telemetry
2023-10-19 11:34:54,454 INFO    MainThread:20162 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-10-19 11:34:54,763 ERROR   MainThread:20162 [wandb_init.py:init():774] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-10-19 11:34:54,835 ERROR   MainThread:20162 [wandb_init.py:init():1183] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/yasin/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/yasin/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-10-19 11:34:55,837 WARNING MsgRouterThr:20162 [router.py:message_loop():77] message_loop has been closed
